#!/bin/sh -u
umask 002

# check-xfs-backup.sh
# Kurt Grosser --- thekurtgrosser@gmail.com --- kurtgrosser.com
# Script that verifys the XFS backup created for
# CST Linux II Assignment 4.


echo Check XFS Backup Script
echo -----------------------

echo Generated on: $(date)
echo Generated by: $(whoami)
echo

XFSBackupFile=/mnt/tape/backup
TMPFile=/home/gros0059/Desktop/tmpfile.txt
xfsrestore -f $XFSBackupFile -t -v silent >$TMPFile

echo Checking XFS backup: $XFSBackupFile
echo File details for $XFSBackupFile
ls -l $XFSBackupFile
echo

echo Number of names found: $(wc $TMPFile | awk '{print $1}')
echo

echo First five names found:
echo
head -5 $TMPFile
echo

echo Last five names found:
echo
tail -5 $TMPFile
echo

rm -rf $TMPFile
echo END OF FILE 