echo Starting CPU Stress Test...
sum /dev/zero & sum /dev/zero & sum /dev/zero & sum /dev/zero & sum /dev/zero & sum /dev/zero & sum /dev/zero & sum /dev/zero &
echo Listing running process to show instances running....
ps
echo Running the CPU Test for 10 seconds...
sleep 10
pkill sum
echo Program has been killed.
